In [69]:
Image(url='https://github.com/Alam-A99/Visualisation/blob/main/1-5.%20Cikal%20Akal%20-%20Black%20copy.png?raw=true')

# PANDAS
Library Pandas memiliki dua tipe struktur data untuk versi terbaru yaitu Series dan Data Frame serta satu deprecated struktur data yaitu Panel (deprecated). 

## Series

Series diibaratkan sebagai array satu dimensi sama halnya dengan numpy array, hanya bedanya mempunyai index dan kita dapat mengontrol index dari setiap elemen tersebut. Sedangkan data frame merupakan array dua dimensi dengan baris dan kolom. Struktur data ini merupakan cara paling standar untuk menyimpan data dalam bentuk tabel/data tabular. Dapat disimpulkan, bahwa Pandas merupakan library analisis data yang diperlukan untuk membersihkan data mentah ke dalam sebuah bentuk yang bisa untuk diolah.

1. Series diibaratkan sebagai array satu dimensi sama halnya dengan numpy array, hanya bedanya mempunyai index dan index tersebut dapat kita kontrol dari setiap elemen tersebut.

#1 Series
Parameter  data, diisi dengan data yang akan dibuat series. Struktur data yang bisa ditampung berupa integer, float, dan juga string. parameter index, diisi dengan index dari series. Jumlah index harus sama dengan jumlah data. Jika kita tidak mengisi parameter index, maka series akan memiliki index integer seperti halnya array biasa. Parameter dtype, diisi dengan tipe data dari series, dan parameter copy untuk copy data, secara default akan bernilai false.

pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)


In [1]:
# 1. contoh Series
import pandas as pd  #pastikan running dulu pandas dan numpy
import numpy as np
ds = pd.Series([2, 4, 6, 8, 10]) #menampilkan array 1-deimensi

print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [27]:
data = pd.Series(['a','b','c']) #!sS
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)

print(data)
print(data_np)

#mengatur indeks pada numpy array data-np di atas
data_np = pd.Series(np1, index=[2,3,4]) 
print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    z
dtype: object
2    x
3    y
4    z
dtype: object


In [19]:
# contoh operasi
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2  #operasi jumlah
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [1]:
#konver pandas module Series ke python list
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type")
print(ds)
print(type(ds))
print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))



Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>


In [17]:
#convert a NumPy array to a Pandas series
import numpy as np
import pandas as pd
np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64


#### Program pandas menghitung minimum, persentil 25, median, persentil 75 dan maksimum dari series

In [37]:
# https://numpy.org/doc/1.16/reference/generated/numpy.random.RandomState.html

import pandas as pd
import numpy as np
num_state = np.random.RandomState(100)   #generate angka random
num_series = pd.Series(num_state.normal(10, 4, 20))

print(num_series)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64


In [63]:
# get the image
Image(url="https://media.geeksforgeeks.org/wp-content/uploads/dataSER-1.png", width=500, height=300)

In [33]:
import pandas as pd
import numpy as np
num_state = np.random.RandomState(100) 
num_series = pd.Series(num_state.normal(10, 4, 20))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0, 25, 50, 75, 100])
print("\nMinimum, persentil-25, median, persentil-75, and maksimum data series:")
print(result)

Original Series:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimum, persentil-25, median, persentil-75, and maksimum data series:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


### Jenis-jenis series pandas dapat dilihat pada link

https://pandas.pydata.org/docs/reference/api/pandas.Series.describe.html

### SILAKAN MEMPELAJARI JENIS-JENIA SERIES YANG LAIN, Pastikan bahwa setiap step dipahami dengan baik. 

In [ ]:
# SOAL LATIHAN Nomor_0, berikan minimal 7 contoh jenis pandas.series yang lain

# Data Frame
Data frame merupakan tabel/data tabular dengan array dua dimensi yaitu baris dan kolom. Struktur data ini merupakan cara paling standar untuk menyimpan data. Setiap kolom pada data frame merupakan objek dari Series, dan baris terdiri dari elemen yang ada pada Series.

*pandas.DataFrame(data, index, columns, dtype, copy)*
- index merupakan label untuk baris
- columns merupakan label untuk kolom
- dtype merupakan tipe data per kolom
- copy digunakan untuk menyalin data, defaultnya False

In [52]:
Image(url='https://e6v4p8w2.rocketcdn.me/wp-content/uploads/2020/05/What-is-Pandas-Dataframe.png', width=600, height=400)

In [47]:
#generate DataFrame df
dates = pd.date_range("20210101", periods=12) #buat tabel data tahun 2021
dates
df = pd.DataFrame(np.random.randn(12, 5), index=dates, columns=list("ABCDF")) 
# angka 12 sama dengan periods baris 1, 5 sesuai dengan jumlah kolom
df

A         B         C         D         F
2021-01-01 -1.273804 -1.720169  0.446024  0.092756 -0.105153
2021-01-02 -0.250388  1.704803  1.937308 -1.247349 -0.137108
2021-01-03  0.372312 -0.493572 -1.418603  0.058592 -1.214880
2021-01-04  0.471890  1.568787 -1.968410 -1.598385  0.696232
2021-01-05  0.797063 -0.211012  0.484663 -0.381633  1.090844
2021-01-06  0.568444 -1.106250 -1.676460 -0.327235 -0.244653
2021-01-07 -0.673781 -0.568840 -0.021757  0.892086 -1.218463
2021-01-08 -0.037467  1.915602 -0.896147 -0.549109  1.069307
2021-01-09  0.597420 -0.650501 -0.686583 -0.667663 -0.657284
2021-01-10 -1.783996 -0.145875 -0.628139 -0.007983  0.695997
2021-01-11  0.175716  1.287484 -1.082421  1.205474 -0.754486
2021-01-12 -0.700512 -0.836212 -1.112997 -0.581123 -0.506306

In [69]:
#SOAL LATIHAN Nomor_1, carilah error pada coding berikut dan perbaiki

df1 = pd.DataFrame(
    {
        "A": 4.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(5)), dtype="float32"),
        "D": np.array([2] * 5, dtype="int32"),
        "E": pd.Categorical(["kami", "mahasiswa", "bisnis", "digital"]),
        "F": "unm",
    }
)
df1

ValueError: All arrays must be of the same length

In [66]:
df1.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

#### View Data


In [73]:
df.head()  #top data df

A         B         C         D         F
2021-01-01 -1.273804 -1.720169  0.446024  0.092756 -0.105153
2021-01-02 -0.250388  1.704803  1.937308 -1.247349 -0.137108
2021-01-03  0.372312 -0.493572 -1.418603  0.058592 -1.214880
2021-01-04  0.471890  1.568787 -1.968410 -1.598385  0.696232
2021-01-05  0.797063 -0.211012  0.484663 -0.381633  1.090844

In [72]:
df.tail(3) #bottom df

A         B         C         D         F
2021-01-10 -1.783996 -0.145875 -0.628139 -0.007983  0.695997
2021-01-11  0.175716  1.287484 -1.082421  1.205474 -0.754486
2021-01-12 -0.700512 -0.836212 -1.112997 -0.581123 -0.506306

In [75]:
df.index

Index(['A', 'B', 'C', 'D', 'F'], dtype='object')

In [76]:
df.columns

Index(['A', 'B', 'C', 'D', 'F'], dtype='object')

In [80]:
df.to_numpy()  #konver df ke numpy

array([[-1.27380445, -1.72016903,  0.44602361,  0.09275558, -0.10515298],
       [-0.25038761,  1.70480279,  1.93730774, -1.24734852, -0.13710834],
       [ 0.37231205, -0.49357191, -1.41860291,  0.05859187, -1.2148797 ],
       [ 0.47188957,  1.56878749, -1.9684098 , -1.59838521,  0.6962322 ],
       [ 0.79706259, -0.21101214,  0.48466332, -0.38163313,  1.09084404],
       [ 0.56844414, -1.10624992, -1.67645955, -0.32723499, -0.24465307],
       [-0.67378122, -0.56884021, -0.02175697,  0.89208575, -1.21846329],
       [-0.03746698,  1.91560244, -0.89614748, -0.54910851,  1.06930697],
       [ 0.59742011, -0.65050091, -0.68658309, -0.66766331, -0.65728428],
       [-1.78399569, -0.14587506, -0.6281391 , -0.00798268,  0.69599712],
       [ 0.17571648,  1.28748351, -1.08242149,  1.20547374, -0.75448637],
       [-0.70051227, -0.83621243, -1.1129966 , -0.58112313, -0.50630615]])

In [96]:
import pandas as pd
df2 = pd.DataFrame({
        'nama':['alam','beni','chalik','dewi','eka','fani', 'gun'],
        'umur':[23,34,19,29,32,40,44],
        'propinsi':[' Sulsel','Jatim','DKI','Bali','Jabar','NTT', 'Papua'] })
df2

nama  umur propinsi
0    alam    23   Sulsel
1    beni    34    Jatim
2  chalik    19      DKI
3    dewi    29     Bali
4     eka    32    Jabar
5    fani    40      NTT
6     gun    44    Papua

##### Soal Latihan 2
Tampilkan 3 data pertama dari df2 di atas


In [92]:
#Jawaban No.2


##### Soal Latihan 3
Tampilkan 2 data terakhir dari df.2 di atas

In [93]:
# Jawaban No.3

### describe() 
menampilkan statistik singkat dari data


In [97]:
df2.describe()

umur
count   7.000000
mean   31.571429
std     8.847921
min    19.000000
25%    26.000000
50%    32.000000
75%    37.000000
max    44.000000

#### Cara import data 

1. Import pandas
2. Definisikan variabel untuk menyimpan path url atau file dataset (dalam folder)
3. Gunakan method read_csv untuk mengimport data (tipe file.csv), pastikan mengetahui atribut data. 

In [19]:
import pandas as pd
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
df = pd.read_csv(url, header=None)
df.head()     #bandingkan dengan perintah print(df.head())

0    1            2    3    4     5            6    7      8     9   ...  \
0   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
1   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
2   1    ?  alfa-romero  gas  std   two    hatchback  rwd  front  94.5  ...   
3   2  164         audi  gas  std  four        sedan  fwd  front  99.8  ...   
4   2  164         audi  gas  std  four        sedan  4wd  front  99.4  ...   

    16    17    18    19    20   21    22  23  24     25  
0  130  mpfi  3.47  2.68   9.0  111  5000  21  27  13495  
1  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500  
2  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500  
3  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950  
4  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450  

[5 rows x 26 columns]

### Link Database 

https://archive.ics.uci.edu/ml/machine-learning-databases/

In [32]:

url = "https://github.com/Alam-A99/Visualisation/blob/main/dataset_visualisasi-indonesia.csv"
df = pd.read_html(url)   #membaca file dari link
df

[     Unnamed: 0  kode_negara     negara  kode_kategori        kategori  \
 0           NaN          101  Indonesia           5312  Area harvested   
 1           NaN          101  Indonesia           5312  Area harvested   
 2           NaN          101  Indonesia           5312  Area harvested   
 3           NaN          101  Indonesia           5312  Area harvested   
 4           NaN          101  Indonesia           5312  Area harvested   
 ..          ...          ...        ...            ...             ...   
 821         NaN          101  Indonesia           5510      Production   
 822         NaN          101  Indonesia           5510      Production   
 823         NaN          101  Indonesia           5510      Production   
 824         NaN          101  Indonesia           5510      Production   
 825         NaN          101  Indonesia           5510      Production   
 
      kode_komoditas                komoditas  kode_tahun  tahun  satuan  \
 0               486  

### SOAL LATIHAN 4
SILAKAN MENGEKPLORASI LEBIH JAUH FUNGSI-FUNGSI PANDAS YANG LAIN SEPERTI BERIKUT, BERIKAN CONTOH MASING-MASING MINIMAL 2.

- Pandas Index
- Pandas String and Regular Expression
- Pandas Joining and merging DataFrames
- Pandas Time Series
- Pandas Filter
- Pandas Grouping and Aggregating
- Pandas Missing Values
- Pandas Style